In [1]:
import pandas as pd
import numpy as np
import timm
import torchvision.transforms as T

from wildlife_tools.features import SuperPointExtractor, SiftExtractor, AlikedExtractor, DiskExtractor, DeepFeatures
from wildlife_tools.similarity import CosineSimilarity, MatchLOFTR, MatchLightGlue
from wildlife_tools.data.dataset import ImageDataset
from wildlife_tools.similarity.wildfusion import SimilarityPipeline, WildFusion
from wildlife_tools.similarity.calibration import IsotonicCalibration

metadata = {'metadata':  pd.read_csv('../tests/TestDataset/metadata.csv'), 'root': '../tests/TestDataset'}
transform = T.Compose([T.Resize([224, 224]), T.ToTensor()])
dataset = ImageDataset(**metadata, transform=transform)


# WildFusion
- Run wildfusion as mean of
    - LightGlue + SuperPoint
    - LightGlue + ALIKED
    - LightGlue + DISK
    - LightGlue + SIFT
    - LOFTR
    - Deep features of MegaDescriptor-L

Additionally, shortlist is created using MegaDescriptor-L scores. It can be used to significantly speed up the matching pipelines by using only `B` samples from database per query, which are selected based on score in the shortlist.

In [ ]:
pipelines = [

    SimilarityPipeline(
        matcher = MatchLightGlue(features='superpoint'),
        extractor = SuperPointExtractor(),
        transform = T.Compose([
            T.Resize([512, 512]),
            T.ToTensor()
        ]),
        calibration = IsotonicCalibration()
    ),

    SimilarityPipeline(
        matcher = MatchLightGlue(features='aliked'),
        extractor = AlikedExtractor(),
        transform = T.Compose([
            T.Resize([512, 512]),
            T.ToTensor()
        ]),
        calibration = IsotonicCalibration()
    ),

    SimilarityPipeline(
        matcher = MatchLightGlue(features='disk'),
        extractor = DiskExtractor(),
        transform = T.Compose([
            T.Resize([512, 512]),
            T.ToTensor()
        ]),
        calibration = IsotonicCalibration()
    ),

    SimilarityPipeline(
        matcher = MatchLightGlue(features='sift'),
        extractor = SiftExtractor(),
        transform = T.Compose([
            T.Resize([512, 512]),
            T.ToTensor()
        ]),
        calibration = IsotonicCalibration()
    ),

    SimilarityPipeline(
        matcher = MatchLOFTR(pretrained='outdoor'),
        extractor = None,
        transform = T.Compose([
            T.Resize([512, 512]),
            T.Grayscale(),
            T.ToTensor(),
        ]),
        calibration = IsotonicCalibration()
    ),

    SimilarityPipeline(
        matcher = CosineSimilarity(),
        extractor = DeepFeatures(
            model = timm.create_model('hf-hub:BVRA/wildlife-mega-L-384', num_classes=0, pretrained=True)
        ),
        transform = T.Compose([
            T.Resize(size=(384, 384)),
            T.ToTensor(),
            T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ]),
        calibration = IsotonicCalibration()
    ),
]


priority_pipeline =  SimilarityPipeline(
    matcher = CosineSimilarity(),
    extractor = DeepFeatures(
        model = timm.create_model('hf-hub:BVRA/wildlife-mega-L-384', num_classes=0, pretrained=True)
    ),
    transform = T.Compose([
        T.Resize(size=(384, 384)),
        T.ToTensor(),
        T.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]),
)

wildfusion = WildFusion(calibrated_pipelines = pipelines, priority_pipeline = priority_pipeline)

In [3]:
wildfusion.fit_calibration(dataset, dataset)

100%|█████████████████████████████████████████████████████████████████| 1/1 [00:14<00:00, 14.69s/it]


### Basic WildFusion
- Run for all pairs
- Note that there are ones at a diagonal at the query and database that are the same datasets.

In [4]:
wildfusion(dataset, dataset)

100%|█████████████████████████████████████████████████████████████████| 1/1 [00:14<00:00, 14.92s/it]


array([[1.00000000e+00, 8.41624476e-01, 8.53761989e-02, 2.58286972e-03],
       [8.45939177e-01, 1.00000000e+00, 2.93104603e-03, 1.28648551e-02],
       [5.72058793e-02, 2.93104603e-03, 1.00000000e+00, 6.89334981e-01],
       [3.01374998e-04, 1.28648551e-02, 6.97637682e-01, 1.00000000e+00]])

### Accelerated WildFusion

In [5]:
wildfusion(dataset, dataset, B=1)

100%|█████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.92s/it]


array([[  1., -inf, -inf, -inf],
       [-inf,   1., -inf, -inf],
       [-inf, -inf,   1., -inf],
       [-inf, -inf, -inf,   1.]], dtype=float32)

In [6]:
wildfusion(dataset, dataset, B=2)

100%|█████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.89s/it]


array([[1.        , 0.84016925,       -inf,       -inf],
       [0.85628253, 1.        ,       -inf,       -inf],
       [      -inf,       -inf, 1.        , 0.68457514],
       [      -inf,       -inf, 0.69002765, 1.        ]], dtype=float32)